spring.application.name=api-gateway

server.port=8080

# =========================
# JWT
# =========================

jwt.secret=MySuperSecretKeyForCafeOrderingSystem2026SecureKey

# =========================
# API KEY
# =========================

api.key=abc123